import { useEffect, useState } from 'react'
import { api, errorMessage } from '../api/client'
import { EmptyState, Notice, Panel } from '../components/Primitives'
import AdminLiveQueueOverview from '../components/AdminLiveQueueOverview'

const tabs = ['Live Queue', 'Departments', 'Doctors', 'Slot templates', 'Analytics']
const emptyDoctor = { name: '', email: '', password: '', phone: '', departmentId: '', specialization: '', avgConsultMinutes: 15 }
const emptySlot = { doctorId: '', dayOfWeek: 'MONDAY', startTime: '09:00', endTime: '12:00', slotCapacity: 20 }
export default function AdminDashboard() {
  const [tab, setTab] = useState(tabs[0]); const [departments, setDepartments] = useState([]); const [doctors, setDoctors] = useState([]); const [slots, setSlots] = useState([])
  const [departmentName, setDepartmentName] = useState(''); const [editingDepartment, setEditingDepartment] = useState(null)
  const [doctorForm, setDoctorForm] = useState(emptyDoctor); const [editingDoctor, setEditingDoctor] = useState(null)
  const [slotForm, setSlotForm] = useState(emptySlot); const [editingSlot, setEditingSlot] = useState(null)
  const [error, setError] = useState(''); const [success, setSuccess] = useState(''); const [busy, setBusy] = useState(false)
  const refresh = async () => { const [d, docs, s] = await Promise.all([api.get('/api/departments'), api.get('/api/admin/doctors'), api.get('/api/admin/slots')]); setDepartments(d.data); setDoctors(docs.data); setSlots(s.data) }
  useEffect(() => { refresh().catch((e) => setError(errorMessage(e))) }, [])
  const run = async (fn, message) => { setError(''); setSuccess(''); setBusy(true); try { await fn(); await refresh(); setSuccess(message) } catch (e) { setError(errorMessage(e)) } finally { setBusy(false) } }
  const saveDepartment = (e) => { e.preventDefault(); run(() => editingDepartment ? api.put(`/api/admin/departments/${editingDepartment.id}`, { name: departmentName }) : api.post('/api/admin/departments', { name: departmentName }), editingDepartment ? 'Department updated.' : 'Department added.').then(() => { setDepartmentName(''); setEditingDepartment(null) }) }
  const saveDoctor = (e) => { e.preventDefault(); const payload = { ...doctorForm, departmentId: Number(doctorForm.departmentId), avgConsultMinutes: Number(doctorForm.avgConsultMinutes) }; run(() => editingDoctor ? api.put(`/api/admin/doctors/${editingDoctor.id}`, { departmentId: payload.departmentId, specialization: payload.specialization, avgConsultMinutes: payload.avgConsultMinutes }) : api.post('/api/admin/doctors', payload), editingDoctor ? 'Doctor profile updated.' : 'Doctor account created.').then(() => { setDoctorForm(emptyDoctor); setEditingDoctor(null) }) }
  const saveSlot = (e) => { e.preventDefault(); const payload = { ...slotForm, doctorId: Number(slotForm.doctorId), slotCapacity: Number(slotForm.slotCapacity) }; run(() => editingSlot ? api.put(`/api/admin/slots/${editingSlot.id}`, payload) : api.post('/api/admin/slots', payload), editingSlot ? 'Slot template updated.' : 'Slot template created.').then(() => { setSlotForm(emptySlot); setEditingSlot(null) }) }
  const beginDoctorEdit = (d) => { setEditingDoctor(d); setDoctorForm({ ...emptyDoctor, departmentId: String(d.departmentId), specialization: d.specialization, avgConsultMinutes: d.avgConsultMinutes }); document.getElementById('doctor-form')?.scrollIntoView({ behavior: 'smooth' }) }
  const beginSlotEdit = (s) => { setEditingSlot(s); setSlotForm({ doctorId: String(s.doctorId), dayOfWeek: s.dayOfWeek, startTime: s.startTime.slice(0, 5), endTime: s.endTime.slice(0, 5), slotCapacity: s.slotCapacity }); document.getElementById('slot-form')?.scrollIntoView({ behavior: 'smooth' }) }
  const remove = (label, url) => { if (window.confirm(`Delete ${label}?`)) run(() => api.delete(url), `${label} deleted.`) }
  return <div className="space-y-6">
    {(error || success) && <Notice tone={success ? 'success' : 'error'}>{success || error}</Notice>}
    <div className="flex flex-wrap gap-2 rounded-2xl border border-slate-200 bg-white p-2">{tabs.map((item) => <button key={item} className={`tab-button ${tab === item ? 'tab-active' : ''}`} onClick={() => setTab(item)}>{item}</button>)}</div>
    {tab === 'Live Queue' && <AdminLiveQueueOverview />}
    {tab === 'Departments' && <Panel title="Departments" hint="Organize the services patients can browse.">
      <form className="mb-5 flex flex-wrap gap-3" onSubmit={saveDepartment}><input className="field max-w-sm" required maxLength="100" placeholder="Department name" value={departmentName} onChange={(e) => setDepartmentName(e.target.value)} /><button className="button-primary" disabled={busy}>{editingDepartment ? 'Save department' : 'Add department'}</button>{editingDepartment && <button type="button" className="button-secondary" onClick={() => { setEditingDepartment(null); setDepartmentName('') }}>Cancel</button>}</form>
      {departments.length ? <div className="divide-y divide-slate-100">{departments.map((d) => <div className="flex items-center justify-between py-3" key={d.id}><span className="font-semibold text-ink">{d.name}</span><div className="flex gap-2"><button className="button-small" onClick={() => { setEditingDepartment(d); setDepartmentName(d.name) }}>Edit</button><button className="button-small button-danger" onClick={() => remove(d.name, `/api/admin/departments/${d.id}`)}>Delete</button></div></div>)}</div> : <EmptyState title="No departments yet">Add a department before setting up doctors.</EmptyState>}
    </Panel>}
    {tab === 'Doctors' && <div className="space-y-6"><Panel title={editingDoctor ? 'Edit doctor profile' : 'Add a doctor'} hint="Doctor accounts can sign in to manage their own queue.">
      <form id="doctor-form" className="grid gap-4 sm:grid-cols-2" onSubmit={saveDoctor}>{!editingDoctor && <><label className="field-label">Doctor name<input className="field" required value={doctorForm.name} onChange={(e) => setDoctorForm({ ...doctorForm, name: e.target.value })} /></label><label className="field-label">Email<input className="field" type="email" required value={doctorForm.email} onChange={(e) => setDoctorForm({ ...doctorForm, email: e.target.value })} /></label><label className="field-label">Temporary password<input className="field" type="password" minLength="8" required value={doctorForm.password} onChange={(e) => setDoctorForm({ ...doctorForm, password: e.target.value })} /></label><label className="field-label">Phone<input className="field" value={doctorForm.phone} onChange={(e) => setDoctorForm({ ...doctorForm, phone: e.target.value })} /></label></>}
        <label className="field-label">Department<select className="field" required value={doctorForm.departmentId} onChange={(e) => setDoctorForm({ ...doctorForm, departmentId: e.target.value })}><option value="">Choose department</option>{departments.map((d) => <option key={d.id} value={d.id}>{d.name}</option>)}</select></label><label className="field-label">Specialization<input className="field" required value={doctorForm.specialization} onChange={(e) => setDoctorForm({ ...doctorForm, specialization: e.target.value })} /></label><label className="field-label">Average consultation (minutes)<input className="field" type="number" min="1" required value={doctorForm.avgConsultMinutes} onChange={(e) => setDoctorForm({ ...doctorForm, avgConsultMinutes: e.target.value })} /></label>
        <div className="flex items-end gap-2"><button className="button-primary" disabled={busy}>{editingDoctor ? 'Save profile' : 'Create doctor'}</button>{editingDoctor && <button type="button" className="button-secondary" onClick={() => { setEditingDoctor(null); setDoctorForm(emptyDoctor) }}>Cancel</button>}</div>
      </form></Panel>
      <Panel title="Doctor directory" hint={`${doctors.length} doctor${doctors.length === 1 ? '' : 's'} configured`}>
        {doctors.length ? <div className="overflow-x-auto"><table className="data-table"><thead><tr><th>Doctor</th><th>Department</th><th>Specialization</th><th>Avg. visit</th><th /></tr></thead><tbody>{doctors.map((d) => <tr key={d.id}><td><div className="font-semibold text-ink">Dr. {d.name}</div><div className="text-xs text-slate-400">{d.email}</div></td><td>{d.department}</td><td>{d.specialization}</td><td>{d.avgConsultMinutes} min</td><td><div className="flex gap-2"><button className="button-small" onClick={() => beginDoctorEdit(d)}>Edit</button><button className="button-small button-danger" onClick={() => remove(`Dr. ${d.name}`, `/api/admin/doctors/${d.id}`)}>Delete</button></div></td></tr>)}</tbody></table></div> : <EmptyState title="No doctors yet">Create the first doctor account for your clinic.</EmptyState>}
      </Panel></div>}
    {tab === 'Slot templates' && <div className="space-y-6"><Panel title={editingSlot ? 'Edit slot template' : 'Create slot template'} hint="Set a recurring weekly clinic window and its daily booking capacity.">
      <form id="slot-form" className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3" onSubmit={saveSlot}><label className="field-label">Doctor<select className="field" required value={slotForm.doctorId} onChange={(e) => setSlotForm({ ...slotForm, doctorId: e.target.value })}><option value="">Choose doctor</option>{doctors.map((d) => <option key={d.id} value={d.id}>Dr. {d.name}</option>)}</select></label><label className="field-label">Day<select className="field" value={slotForm.dayOfWeek} onChange={(e) => setSlotForm({ ...slotForm, dayOfWeek: e.target.value })}>{['MONDAY', 'TUESDAY', 'WEDNESDAY', 'THURSDAY', 'FRIDAY', 'SATURDAY', 'SUNDAY'].map((d) => <option key={d}>{d}</option>)}</select></label><label className="field-label">Capacity<input className="field" type="number" min="1" required value={slotForm.slotCapacity} onChange={(e) => setSlotForm({ ...slotForm, slotCapacity: e.target.value })} /></label><label className="field-label">Starts<input className="field" type="time" required value={slotForm.startTime} onChange={(e) => setSlotForm({ ...slotForm, startTime: e.target.value })} /></label><label className="field-label">Ends<input className="field" type="time" required value={slotForm.endTime} onChange={(e) => setSlotForm({ ...slotForm, endTime: e.target.value })} /></label><div className="flex items-end gap-2"><button className="button-primary" disabled={busy}>{editingSlot ? 'Save template' : 'Create template'}</button>{editingSlot && <button className="button-secondary" type="button" onClick={() => { setEditingSlot(null); setSlotForm(emptySlot) }}>Cancel</button>}</div></form></Panel>
      <Panel title="Weekly schedule" hint="Overlapping templates for one doctor and day are prevented.">{slots.length ? <div className="overflow-x-auto"><table className="data-table"><thead><tr><th>Doctor</th><th>Day</th><th>Time</th><th>Capacity</th><th /></tr></thead><tbody>{slots.map((s) => <tr key={s.id}><td>Dr. {doctors.find((d) => d.id === s.doctorId)?.name || `#${s.doctorId}`}</td><td>{s.dayOfWeek}</td><td>{s.startTime.slice(0, 5)}–{s.endTime.slice(0, 5)}</td><td>{s.slotCapacity}</td><td><div className="flex gap-2"><button className="button-small" onClick={() => beginSlotEdit(s)}>Edit</button><button className="button-small button-danger" onClick={() => remove('slot template', `/api/admin/slots/${s.id}`)}>Delete</button></div></td></tr>)}</tbody></table></div> : <EmptyState title="No schedules yet">Add a slot template to make appointment times available.</EmptyState>}</Panel></div>}
    {tab === 'Analytics' && <Analytics />}
  </div>
}

function Analytics() {
  const [items, setItems] = useState([]); const [error, setError] = useState(''); const [busy, setBusy] = useState(true)
  useEffect(() => { api.get('/api/admin/analytics').then(({ data }) => setItems(data)).catch((e) => setError(errorMessage(e))).finally(() => setBusy(false)) }, [])
  return <Panel title="Today’s clinic activity" hint="Current queue counts and measured service metrics by doctor.">{error ? <Notice>{error}</Notice> : busy ? <div className="skeleton h-24" /> : items.length ? <div className="overflow-x-auto"><table className="data-table"><thead><tr><th>Doctor</th><th>Waiting</th><th>Served</th><th>Average wait</th><th>No-shows</th><th>No-show rate</th></tr></thead><tbody>{items.map((i) => <tr key={i.doctorId}><td className="font-semibold text-ink">Dr. {i.doctorName}</td><td>{i.waiting}</td><td>{i.served}</td><td>{i.averageWaitMinutes} min</td><td>{i.noShows}</td><td>{i.noShowRate}%</td></tr>)}</tbody></table></div> : <EmptyState title="No activity yet">Doctor and queue activity will appear here throughout the day.</EmptyState>}</Panel>
}
